language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - deps=low
    - deps=high

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
    - composer self-update
    - if [ "$deps" = "high" ]; then composer update --prefer-source -n; fi;
    - if [ "$deps" = "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable -n; fi;

script:
    - ./vendor/bin/phpunit

